### ISSUE TITLE
а почему с  minSdkVersion 14 ?

### ISSUE THREAD

**Issue by aratj** [Arello-Mobile/MoxySample#4]
Есть проект с моей MVP , хотел использовать вашу.
но, смотрю ругается.

Variant Debug has a dependency on version 4.0.1.2 of the legacy com.google.android Maven artifact, which corresponds to API level 14. This is not compatible with min SDK of this module, which is 9. Please use the 'gradle dependencies' task to debug your dependencies graph.

Да, знаю, но люди вообще хотят еще поддержку от API 9-10 (

**Comment by aratj** [comment]
Упс, этот вопрос наверное не к семплу а, скорее самой библиотеки ,

**Comment by senneco** [comment]
Возможно, это артефакт. Потому что в [moxy/build.gradle](https://github.com/Arello-Mobile/Moxy/blob/master/moxy/build.gradle) указана зависимость:

`compile 'com.google.android:android:1.5_r3'`

Но в то же время есть зависимость:

`testCompile 'com.google.android:android:4.0.1.2'`

Посмотрю, что можно сделать – может быть для тестов вовсе не нужен Android 4+

**Comment by senneco** [comment]
Теперь min sdk - 3 :D

**Comment by aratj** [comment]
Круто, спасибо )
