### ISSUE TITLE
Presenter1 -> View -> Presenter2

### ISSUE THREAD

**Issue by RamilGabdrakhmanov** [Arello-Mobile/MoxySample#5]
Правильно ли я понимаю, что [тут](https://github.com/Arello-Mobile/MoxySample/blob/2ab4b1669645b350226ad0ce55d86002cde6a8ab/app/src/main/java/com/arellomobile/github/ui/activities/HomeActivity.java#L175) получилась свять Presenter1 -> View -> Presenter2? 
На DroidCon вы говорили, что лучше связывать два презентера через модель. Как это можно тут организовать?

**Comment by senneco** [comment]
Хорошее замечание. Но нет, это не такой тип общения. Как можно заметить, команда `HomeView.showDetails()` уходит из `HomePresenter` и меняет только отображение -- влияет только на флаг адаптера `RepositoriesAdapter.mSelection`, который влияет только на отображение, но ни на какой презентер. Поэтому ничто не нарушено =)
