### ISSUE TITLE
How to Run, error on Build step ?

### ISSUE THREAD

**Issue by PushoN** [Arello-Mobile/MoxySample#6]
I get error on Build

Gradle 'MoxySample' project refresh failed
Error:Cause: unable to find valid certification path to requested target

**Comment by senneco** [comment]
@PushoN could you get more info? I can't reproduce this exception. May be android studio version or something else?

**Comment by PushoN** [comment]
@senneco 
Yeah, Android Studio 2.2, gradle 2.1.14. jdk 1.8

**Comment by senneco** [comment]
Hm, I can't reproduce still. Googling said that its may be Android Studio bug. Could you try [this](http://stackoverflow.com/a/33748030/1396039) solution?

**Comment by PushoN** [comment]
@senneco so, i've updated today Android Studio to 2.2.1, Gradle and some Android SDK tools, and now it works. Thank you for your reply.

**Comment by senneco** [comment]
Great 😉
